version: "3"

services:
  
  web:
    build: .
    volumes:
      - '.:/usr/src/app/'
    ports:
      - "3000:3000"
    env_file:
      - .env/development/web
      - .env/development/database
      
  redis:
    image: redis
    volumes: 
      - rd_data:/data

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
  rd_data: