version: '3'

services:
  
  web:
    build: .
    volumes:
      - '.:/usr/src/app/'
      - gem_cache:/gems
    ports:
      - '3000:3000'
      - '4000:4000'
    environment: 
      - BUNDLE_PATH=/gems/vendor
    env_file:
      - .env/development/web
      - .env/development/database
      
  redis:
    image: redis
    volumes: 
      - rd_data:/data

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes: 
      - db_data:/var/lib/postgresql/data
  
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
    ports:
      - '5900:5900'

volumes: 
  db_data:
  gem_cache:
  rd_data: